[package]
name = "astronomy"
version = "0.1.0"
authors = ["Chase <cjopsahl99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astro = "2.0.0"
chrono = "0.4"
quicli = "0.4.0"
structopt = "0.3.20"

